/**
 * Creating a sidebar enables you to:
 *  - render a sidebar for your docs
 *  - create an ordered group of docs
 *  - render a sidebar for multiple docs groups
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
