// ...existing code...
import messageReactionAdd from "./messageReactionAdd.js";
import messageReactionRemove from "./messageReactionRemove.js";
// ...existing code...
client.on("messageReactionAdd", messageReactionAdd.bind(null, { client, database }));
client.on("messageReactionRemove", messageReactionRemove.bind(null, { client, database }));
// ...existing code...

