export default {
  "0058b4c6": [() => import(/* webpackChunkName: "0058b4c6" */ "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json"), "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/docs-175.json")],
  "05d986ad": [() => import(/* webpackChunkName: "05d986ad" */ "@site/docs/containers/index.mdx"), "@site/docs/containers/index.mdx", require.resolveWeak("@site/docs/containers/index.mdx")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "460657e1": [() => import(/* webpackChunkName: "460657e1" */ "@site/docs/runtimes/index.mdx"), "@site/docs/runtimes/index.mdx", require.resolveWeak("@site/docs/runtimes/index.mdx")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "7671ec47": [() => import(/* webpackChunkName: "7671ec47" */ "@site/docs/postgresql/index.mdx"), "@site/docs/postgresql/index.mdx", require.resolveWeak("@site/docs/postgresql/index.mdx")],
  "79dc39c1": [() => import(/* webpackChunkName: "79dc39c1" */ "@site/docs/commands/index.mdx"), "@site/docs/commands/index.mdx", require.resolveWeak("@site/docs/commands/index.mdx")],
  "9dd8a0d2": [() => import(/* webpackChunkName: "9dd8a0d2" */ "@site/src/pages/index.jsx"), "@site/src/pages/index.jsx", require.resolveWeak("@site/src/pages/index.jsx")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "bd7f39ae": [() => import(/* webpackChunkName: "bd7f39ae" */ "@site/docs/config/index.mdx"), "@site/docs/config/index.mdx", require.resolveWeak("@site/docs/config/index.mdx")],
  "c0c12f74": [() => import(/* webpackChunkName: "c0c12f74" */ "@site/docs/custom-commands/index.mdx"), "@site/docs/custom-commands/index.mdx", require.resolveWeak("@site/docs/custom-commands/index.mdx")],
  "f600b847": [() => import(/* webpackChunkName: "f600b847" */ "@site/docs/setup/index.mdx"), "@site/docs/setup/index.mdx", require.resolveWeak("@site/docs/setup/index.mdx")],
  "f8409a7e": [() => import(/* webpackChunkName: "f8409a7e" */ "@site/docs/intro.mdx"), "@site/docs/intro.mdx", require.resolveWeak("@site/docs/intro.mdx")],};
